name: Update README
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/update-readme.yml'
      - 'resume.tex'
      - 'Ava_Hajratwala_resume*.pdf'
      - 'Ava_Hajratwala_resume*.png'
jobs:

  build:
    paths-ignore:
      - 'Ava_Hajratwala_resume*.pdf'
      - 'Ava_Hajratwala_resume*.png'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Compile LaTeX to PDF
        uses: xu-cheng/latex-action@v4
        with:
          root_file: resume.tex

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Change ImageMagick security policy
        run: |
          DQT='"'
          SRC="rights=${DQT}none${DQT} pattern=${DQT}PDF${DQT}"
          RPL="rights=${DQT}read|write${DQT} pattern=${DQT}PDF${DQT}"
          sudo sed -i "s/$SRC/$RPL/" /etc/ImageMagick-6/policy.xml

      - name: Convert PDF to PNG
        run: |
          mv resume.pdf Ava_Hajratwala_resume.pdf
          convert -density 300 Ava_Hajratwala_resume.pdf -background white -alpha remove -flatten -quality 90 Ava_Hajratwala_resume.png

      - name: Push built files to repo
        run: |
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git add Ava_Hajratwala_resume*.*
            git commit -m "Build resume - ${{ github.event.head_commit.message }}"
            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/avahajr/resume.git main

  update-github-readme:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Copy resume to remote repository
        run: |
          git clone https://github.com/avahajr/avahajr.git remote-repo
          rm remote-repo/Ava_Hajratwala_resume*.*
          cp Ava_Hajratwala_resume*.pdf remote-repo/Ava_Hajratwala_resume.pdf
          cp Ava_Hajratwala_resume*.png remote-repo/Ava_Hajratwala_resume.png
          cd remote-repo
          git add -A
          git commit -m "${{ github.event.head_commit.message }}"
          git push https://${{ secrets.UPDATE_README }}@github.com/avahajr/avahajr.git main

  update-portfolio-site:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Copy new resume to portfolio site
        run: |
          git clone https://github.com/avahajr/avahajr.github.io.git portfolio-site
          rm portfolio-site/public/Ava_Hajratwala_resume*.*
          cp Ava_Hajratwala_resume*.pdf portfolio-site/public/Ava_Hajratwala_resume.pdf
          cp Ava_Hajratwala_resume*.png portfolio-site/public/Ava_Hajratwala_resume.png
          cd portfolio-site
          git commit -am "RESUME UPDATE - ${{ github.event.head_commit.message }}"
          git push https://${{ secrets.UPDATE_README }}@github.com/avahajr/avahajr.github.io.git main
