name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Copy README.md to remote repository
        run: |
          git clone https://github.com/avahajr/avahajr.git remote-repo
          cp Ava_Hajratwala_resume_*.pdf remote-repo/Ava_Hajratwala_resume.pdf
          cd remote-repo
          git add Ava_Hajratwala_resume.pdf
          git commit -m "add new global resume (from resume repository)"
          git push https://${{ secrets.UPDATE_README }}@github.com/avahajr/avahajr.git main