name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Copy resume to remote repository
        run: |
          git clone https://github.com/avahajr/avahajr.git remote-repo
          rm remote-repo/Ava_Hajratwala_resume*.*
          cp Ava_Hajratwala_resume_*.pdf remote-repo/Ava_Hajratwala_resume.pdf
          cp Ava_Hajratwala_resume*.png remote-repo/Ava_Hajratwala_resume.png
          cd remote-repo
          git add -A
          git commit -m "${{ github.event.head_commit.message }}"
          git push https://${{ secrets.UPDATE_README }}@github.com/avahajr/avahajr.git main